### ISSUE TITLE
The docs are terrible

### ISSUE THREAD

**Issue by vinniefalco** [cgyarvin/urbit#14]
The documentation reads like an episode of Dirk Gently's Holistic Detective Agency. And not in a good way.

**Comment by cgyarvin** [comment]
You're looking at a very old repo.  Go to urbit.org.

**Comment by vinniefalco** [comment]
Tried to go to urbit.org/docs but the thingy spins in the top left on a white page and nothing happens after 2 minutes

**Comment by cgyarvin** [comment]
Try it again!  Our self hosting is a little flaky.

**Comment by vinniefalco** [comment]
Yes it is working now, thank you

**Comment by cgyarvin** [comment]
Thanks for your patience!

**Comment by vinniefalco** [comment]
The docs are very much improved. The non-sterile, colorful language has been toned down (it did not help understanding). However, it still lacks sufficient rigor to enable someone with no background or knowledge of functional programming to gain profound understanding of Hoon and Nock.

**Comment by cgyarvin** [comment]
I agree.  It's a hard problem which hasn't been solved yet.  I've just
completed a major language revision and will attack this problem further
after completing the major OS revision.  In the meantime, others are also
working on it.
